# Jekyll 配置
title: Glider Record
description: 个人工作生活文档记录
author: Glider
email: your-email@example.com
url: "https://glider110.github.io"
baseurl: "/gliderRecord"

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 主题
theme: minima

# 排除文件
exclude:
  - README.md
  - package.json
  - fix-assets.js
  - node_modules
  - deploy.sh
  - 部署说明.md
  - Gemfile
  - _pages
  - .topwrite
  - book.json
  - deploy.md
  - SUMMARY.md

# Markdown 设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge